# Ansible managed - roles/nginx/files/log_format.conf

# Basically, the default nginx log line, with some additional fields to allow
# better metrics from prometheus-nginxlog-exporter

log_format prom '$remote_addr - $remote_user [$time_local] '
                '"$request" $status $body_bytes_sent '
                '"$http_referer" "$http_user_agent" '
                '$request_length $request_time "$upstream_response_time" '
                '$realip_remote_addr:$realip_remote_port '
                '"$http_x_forwarded_for" $host';
