---

- name: Baseline for all types of systems
  hosts: linux
  become: true

  pre_tasks:
    - name: Preflight check
      ansible.builtin.import_tasks: preflight.yml

  roles:
    - aa_apt_repo
    - aa_base
    - dehydrated
    - mariadb
    - munin
    - nginx
    - nftables
    - ssh
    - users
    - wordpress
