---

- name: Packages
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present

- name: Install backup script
  ansible.builtin.copy:
    dest: "/usr/local/bin/mariadbdump"
    src: mariadbdump
    mode: "a=rx"

- name: Service to backup
  ansible.builtin.copy:
    dest: "/etc/systemd/system/mariadbdump.service"
    mode: "a=r"
    content: |
      # Ansible managed - inline
      [Unit]
      Description=mariadbdump

      [Service]
      Type=oneshot

      ExecStart=/usr/local/bin/mariadbdump
  notify: Reload systemd

- name: Timer to backup
  ansible.builtin.copy:
    dest: "/etc/systemd/system/mariadbdump.timer"
    mode: "a=r"
    content: |
      # Ansible managed - inline
      [Unit]
      Description=mariadbdump

      [Timer]
      OnCalendar=04:00
      RandomizedDelaySec=40min
      FixedRandomDelay=True

      [Install]
      WantedBy=timers.target
  notify: Reload systemd

- name: Ensure systemd services loaded
  ansible.builtin.meta: flush_handlers

- name: Enable timers
  ansible.builtin.systemd_service:
    name: "mariadbdump.timer"
    enabled: true
    state: started

- name: Create databases
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item.key }}"
    state: present
  loop: "{{ mariadb.databases | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create users
  community.mysql.mysql_user:
    column_case_sensitive: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item.key }}"
    password: "{{ lookup('community.general.passwordstore', inventory_hostname + '/' + item.value.passpath, directory='passwordstore') }}"
    # yamllint disable-line rule:line-length
    priv: "{% for k, v in item.value.grants.items() %}{{ k }}:{{ v }}{% if not loop.last %}/{% endif %}{% endfor %}"
    state: present
  loop: "{{ mariadb.users | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
