---

dehydrated:

mariadb:
  databases:
    dsl1:
    test1:
  users:
    dsl1user:
      passpath: mariadb/dsl1user
      grants:
        dsl1.*: ALL
    test1user:
      passpath: mariadb/test1user
      grants:
        test1.*: ALL

nftables:
  monitoring_ports:
    tcp:
      - 4040
      - 4949
      - 9100
  ports:
    tcp:
      - 80
      - 443
  template_type: simple_server

nginx:
  vhosts:
    dimsumlabs.com:
      template_type: generic
      locations:
        /:
          location_type: return
          return: 301 https://www.dimsumlabs.com$request_uri
    hargow.dimsumlabs.com:
      template_type: wordpress
      root: /srv/test1/wordpress

wordpress:
  dsl1:
    version: 6.7.7
    db_user: dsl1user
    db_passpath: mariadb/dsl1user
    salts_passpath: wordpress/dsl1salts
  test1:
    version: 6.7.7
    db_user: test1user
    db_passpath: mariadb/test1user
    salts_passpath: wordpress/test1salts
